import axios from 'axios';
// Import the newly defined Plan interface
import { Student, ChatMessage, Result, Assessment, User, DevelopmentPlan, StudentAttributes, SubjectAttribute, Plan, PlanStatus, Subject, SubmissionPayload } from '../types';

// Use environment variable with fallback to default development URL
const API_URL = import.meta.env.VITE_API_URL || '/api';

export const authService = {
  async login(email: string, password: string): Promise<{ token: string; user: User }> {
    try {
      const response = await axios.post<{ token: string; user: User }>(`${API_URL}/auth/login`, { email, password });
      if (response.data?.token) {
        localStorage.setItem('token', response.data.token);
      }
      if (response.data?.user) {
        localStorage.setItem('user', JSON.stringify(response.data.user));
      }
      return response.data;
    } catch (error: any) {
      throw new Error(error.response?.data?.message || 'Login failed');
    }
  },

  async register(userData: Partial<User>): Promise<{ token: string; user: User }> {
    const data = await fetchData<{ token: string; user: User }>('/auth/register', {
      method: 'POST',
      body: JSON.stringify(userData),
    });

    if (data?.token) {
      localStorage.setItem('token', data.token);
    }
    if (data?.user) {
      localStorage.setItem('user', JSON.stringify(data.user));
    }

    return data;
  },

  logout(): void {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    window.location.href = '/login';
  },

  getCurrentUser(): User | null {
    const userStr = localStorage.getItem('user');
    return userStr ? JSON.parse(userStr) : null;
  }
};


// Helper function for fetch requests
export async function fetchData<T = any>(endpoint: string, options: RequestInit = {}): Promise<T> {
  const token = localStorage.getItem('token');

  const defaultHeaders: HeadersInit = {
    'Content-Type': 'application/json',
  };

  if (token) {
    defaultHeaders['Authorization'] = `Bearer ${token}`;
  }

  const response = await fetch(`${API_URL}${endpoint}`, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({
      message: 'Something went wrong',
    }));
    throw new Error(error.message || `HTTP error! status: ${response.status}`);
  }

  return response.json();
};


// Student services
export const studentService = {
  getStudents: async (subjectId?: string): Promise<Student[]> => { // Added optional subjectId parameter
    const endpoint = subjectId ? `/students?subjectId=${subjectId}` : '/students';
    return fetchData(endpoint);
  },

  getStudent: async (id: string): Promise<Student> => {
    if (!id || id === 'undefined') {
      throw new Error('Student id is required');
    }
    return fetchData<Student>(`/students/${id}`);
  },

  createStudent: async (studentData: Partial<Student>): Promise<Student> => {
    return fetchData<Student>('/students', {
      method: 'POST',
      body: JSON.stringify(studentData),
    });
  },

  updateStudent: async (id: string, studentData: Partial<Student>): Promise<Student> => {
    return fetchData<Student>(`/students/${id}`, {
      method: 'PUT',
      body: JSON.stringify(studentData),
    });
  },

  deleteStudent(id: string): Promise<{ message: string }> {
    return fetchData(`/students/${id}`, {
      method: 'DELETE',
    });
  }
};

// Subject services
export const subjectService = {
  // Get all subjects (for teachers/admins) or enrolled subjects (for students)
  getSubjects: async (): Promise<Subject[]> => {
    return fetchData<Subject[]>('/subjects');
  },

  // Get a single subject by ID with proper access control
  // - Admins can access any subject
  // - Teachers can access subjects they teach
  // - Students can only access subjects they're enrolled in
  getSubjectById: async (id: string): Promise<Subject> => {
    return fetchData<Subject>(`/subjects/${id}`);
  },

  // Get subjects taught by the current teacher
  getTeachingSubjects: async (): Promise<Subject[]> => {
    return fetchData<Subject[]>('/subjects/teaching');
  },
};

// Development services
export const developmentService = {
  // Subject attributes
  getSubjectAttributes: async (subjectId: string): Promise<SubjectAttribute[]> => {
    return fetchData<SubjectAttribute[]>(`/development/attributes/subject/${subjectId}`);
  },

  createSubjectAttribute: async (attributeData: Omit<SubjectAttribute, '_id' | 'createdAt' | 'updatedAt'>): Promise<SubjectAttribute> => {
    // Omit _id, createdAt, updatedAt as they are generated by the backend
    return fetchData<SubjectAttribute>('/development/attributes/subject', {
      method: 'POST',
      body: JSON.stringify(attributeData),
    });
  },

  // Student attributes
  getStudentAttributes: async (studentId: string, subjectId: string): Promise<StudentAttributes> => {
    // This assumes your backend for this endpoint transforms the StudentAttribute array
    // into the StudentAttributes object shape before sending.
    return fetchData<StudentAttributes>(`/development/attributes/student/${studentId}/subject/${subjectId}`);
  },

  updateStudentAttributes: async (studentId: string, attributes: Array<{ attributeId: string; current: number; potential: number }>): Promise<{ message: string }> => {
    // This input type reflects common update patterns. Adjust if your backend expects something else.
    // The return type assumes a success message. Change to StudentAttributes if the backend returns the full updated object.
    return fetchData<{ message: string }>(`/development/attributes/student/${studentId}`, {
      method: 'PUT',
      body: JSON.stringify(attributes),
    });
  },

  // Plans
  getSubjectPlans: async (subjectId: string): Promise<Plan[]> => {
    // This returns plan TEMPLATES associated with a subject
    return fetchData<Plan[]>(`/development/plans/subject/${subjectId}`);
  },

  createSubjectPlan: async (planData: Omit<Plan, '_id' | 'createdAt' | 'updatedAt'>): Promise<Plan> => {
    // Omit _id, createdAt, updatedAt as they are generated by the backend
    return fetchData<Plan>('/development/plans/subject', {
      method: 'POST',
      body: JSON.stringify(planData),
    });
  },

  getStudentPlan: async (studentId: string, subjectId: string): Promise<DevelopmentPlan> => {
    // This returns a specific student's instance of a plan, with populated plan details
    if (!studentId || studentId === 'undefined') {
      throw new Error('Student id is required');
    }
    return fetchData<DevelopmentPlan>(`/development/plans/student/${studentId}/subject/${subjectId}`);
  },

  // Get all plans assigned to a student (with optional filter support)
  getAllPlansForStudent: async (studentId: string, status?: string): Promise<DevelopmentPlan[]> => {
    if (!studentId || studentId === 'undefined') {
      return [];
    }
    const query = status ? `?status=${encodeURIComponent(status)}` : '';
    return fetchData<DevelopmentPlan[]>(`/development/plans/student/${studentId}${query}`);
  },

  assignPlanToStudent: async (studentId: string, planId: string, subjectId?: string): Promise<DevelopmentPlan> => {
    // This assigns a plan template to a student, creating a StudentPlan document on backend
    const requestBody: { planId: string; subjectId?: string } = { planId };
    
    if (subjectId) {
      requestBody.subjectId = subjectId;
    }
    
    return fetchData<DevelopmentPlan>(`/development/plans/student/${studentId}/assign`, {
      method: 'POST',
      body: JSON.stringify(requestBody),
    });
  },

  updatePlanProgress: async (studentId: string, planId: string, progressData: { currentProgress?: number; status?: PlanStatus; skillProgress?: Array<{ skill: string; currentScore: number }> }): Promise<DevelopmentPlan> => {
    // Adjust progressData type based on what fields can be updated
    return fetchData<DevelopmentPlan>(`/development/plans/student/${studentId}/${planId}/progress`, {
      method: 'PUT',
      body: JSON.stringify(progressData),
    });
  },
};

// Assessment services
export const assessmentService = {
  getAssessments: async (): Promise<Assessment[]> => {
    return fetchData<Assessment[]>('/assessments');
  },

  getAssessment: async (id: string): Promise<Assessment> => {
    return fetchData<Assessment>(`/assessments/${id}`);
  },
    // New function to fetch assessments by subject ID
  getAssessmentsBySubjectId: async (subjectId: string): Promise<Assessment[]> => {
    // This uses the backend route `GET /api/assessments?subjectId=...`
    return fetchData<Assessment[]>(`/assessments?subjectId=${subjectId}`);
  },
  
  createAssessment: async (assessmentData: Omit<Assessment, '_id' | 'createdAt' | 'updatedAt'>): Promise<Assessment> => {
    // Omit _id, createdAt, updatedAt as they are generated by the backend
    return fetchData<Assessment>('/assessments', {
      method: 'POST',
      body: JSON.stringify(assessmentData),
    });
  },

  updateAssessment: async (id: string, assessmentData: Partial<Assessment>): Promise<Assessment> => {
    return fetchData<Assessment>(`/assessments/${id}`, {
      method: 'PUT',
      body: JSON.stringify(assessmentData),
    });
  },

  deleteAssessment: async (id: string): Promise<{ message: string }> => {
    return fetchData<{ message: string }>(`/assessments/${id}`, {
      method: 'DELETE',
    });
  },

  getResults: async (assessmentId: string, studentId?: string): Promise<Result[]> => {
    // Fetches results for a specific assessment, optionally filtered by student
    const url = studentId 
      ? `/assessments/${assessmentId}/results?studentId=${studentId}`
      : `/assessments/${assessmentId}/results`;
    return fetchData<Result[]>(url);
  },

  addResult: async (id: string, resultData: Omit<Result, '_id' | 'createdAt' | 'updatedAt' | 'assessment'>): Promise<Result> => {
    // Omit _id, createdAt, updatedAt; 'assessment' is implied by the URL
    // resultData should include student, expectedMark, actualMark, grade, feedback, submittedDate, externalAssessmentData
    return fetchData<Result>(`/assessments/${id}/results`, {
      method: 'POST',
      body: JSON.stringify(resultData),
    });
  },
};

// Chat services
// Define a type for the unread counts response
export interface UnreadChatCount {
  studentId: string;
  unreadCount: number;
  studentName?: string;  // Optional: if you want to include student name in the response
  lastMessage?: string;  // Optional: if you want to include the last message
  lastMessageTime?: Date; // Optional: if you want to include when the last message was sent
}

// Submission services
// Updated submissionService section for your api.ts file

export const submissionService = {
  submitAssignment: async (submissionData: SubmissionPayload): Promise<any> => {
    const formData = new FormData();
    
    // Essential fields - match backend expectations
    formData.append('assessmentId', submissionData.assessmentId);
    formData.append('studentId', submissionData.studentId);
    formData.append('submissionType', submissionData.submissionType);

    // Handle file uploads
    if (submissionData.submissionType === 'file' && submissionData.file) {
      formData.append('file', submissionData.file);
    } 
    
    // Handle text submissions
    if (submissionData.submissionType === 'text' && submissionData.textContent) {
      formData.append('textContent', submissionData.textContent);
    }

    // Add external assessment data if provided
    if (submissionData.externalAssessmentData) {
      formData.append('externalAssessmentData', JSON.stringify(submissionData.externalAssessmentData));
    }

    // Add result ID if provided
    if (submissionData.result) {
      formData.append('result', submissionData.result);
    }

    // Add additional fields if present
    if (submissionData.originalFilename) {
      formData.append('originalFilename', submissionData.originalFilename);
    }
    if (submissionData.fileType) {
      formData.append('fileType', submissionData.fileType);
    }

    try {
      const response = await fetch(`${API_URL}/submissions`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('token')}`,
        },
        body: formData,
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.message || `HTTP ${response.status}: Failed to submit assignment`);
      }

      return response.json();
    } catch (error) {
      console.error('Submission error:', error);
      throw error;
    }
  },

  getSubmissionDetails: async (submissionId: string) => {
    return fetchData(`/submissions/${submissionId}`);
  },

  getStudentSubmissions: async (studentId: string) => {
    return fetchData(`/submissions/student/${studentId}`);
  },

  reviewSubmission: async (submissionId: string, reviewData: {
    scoreAdjustment?: number;
    feedbackAdjustment?: string;
    finalScore?: number;
    finalGrade?: string;
  }) => {
    return fetchData(`/submissions/${submissionId}/review`, {
      method: 'PUT',
      body: JSON.stringify(reviewData),
    });
  },

  // Fixed endpoint path to match backend
  getPendingSubmissions: async () => {
    return fetchData('/submissions/teacher/pending');
  },

  // Fixed endpoint path to match backend  
  getGradingStats: async (subjectId?: string, timeframe?: string) => {
    const params = new URLSearchParams();
    if (subjectId) params.append('subjectId', subjectId);
    if (timeframe) params.append('timeframe', timeframe);
    
    const queryString = params.toString();
    const endpoint = queryString ? `/submissions/stats?${queryString}` : '/submissions/stats';
    
    return fetchData(endpoint);
  }
};

// Notification services
export const notificationService = {
  getNotifications: async (page = 1, limit = 20, unreadOnly = false) => {
    const params = new URLSearchParams({
      page: page.toString(),
      limit: limit.toString(),
      unreadOnly: unreadOnly.toString()
    });
    
    return fetchData(`/notifications?${params.toString()}`);
  },

  markAsRead: async (notificationId: string) => {
    return fetchData(`/notifications/${notificationId}/read`, {
      method: 'PUT'
    });
  },

  markAllAsRead: async () => {
    return fetchData('/notifications/read-all', {
      method: 'PUT'
    });
  },

  deleteNotification: async (notificationId: string) => {
    return fetchData(`/notifications/${notificationId}`, {
      method: 'DELETE'
    });
  },

  getUnreadCount: async () => {
    return fetchData('/notifications/unread-count');
  }
};

export const chatService = {
  getMessages: async (studentId: string): Promise<ChatMessage[]> => {
    return fetchData<ChatMessage[]>(`/chat/messages/${studentId}`);
  },

  sendMessage: async (studentId: string, content: string): Promise<ChatMessage> => {
    return fetchData<ChatMessage>(`/chat/messages/${studentId}`, {
      method: 'POST',
      body: JSON.stringify({ content }),
    });
  },

  markAsRead: async (studentId: string): Promise<{ message: string }> => {
    return fetchData<{ message: string }>(`/chat/read/${studentId}`, {
      method: 'PUT',
    });
  },

  getUnreadCounts: async (): Promise<UnreadChatCount[]> => {
    // Assuming this returns an array of objects with studentId and unreadCount
    return fetchData<UnreadChatCount[]>('/chat/unread');
  },
};